---
- hosts: api.thelgbtwhip.org.uk
  sudo: no
  roles:
    - transfer-api
    - force-ownership
    - configure-api
    - switch-out-build
  vars:
    php_executable: /usr/bin/php
    doctrine_script: lib/bin/doctrine
    symlink_name: current
    apache_user: www-data
    http_service: nginx
